[package]
name = "chat-rs"
version = "1.0.0"
authors = ["boolean_coercion <booleancoercion@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.8"
crossterm = "0.18"
ctrlc = "3.1"
aes = "0.6"
rand_core = { version="0.5", features=["getrandom"] }
k256 = { version="0.5", features=["ecdh"] }
hkdf = "0.10"
sha2 = "0.9"
anyhow = "1.0"
iced = { version="0.2", features=["tokio"] }
iced_futures = "0.2"
tokio = { version="0.3", features=["full"] }
async-trait = "0.1"
iced_mpsc = { path ="iced_mpsc/" }