[package]
name = "client_term"
version = "0.1.1"
authors = ["boolean_coercion <booleancoercion@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
crossterm = "0.18"
chat-rs = { path = "../" }

[dependencies.tokio]
version = "1.26"
features = ["net", "rt", "rt-multi-thread", "macros"]
