name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build (Ubuntu)
      run: cargo build --verbose
    - name: Run tests (Ubuntu)
      run: cargo test --verbose
  
  build_windows:
    
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build (Windows)
        run: cargo build --verbose
      - name: Run tests (Windows)
        run: cargo test --verbose
