name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build library (Ubuntu)
      run: cargo build --verbose

    - name: Build server (Ubuntu)
      run: cargo build --verbose
      working-directory: ./server
        
    - name: Build client_term (Ubuntu)
      run: cargo build --verbose
      working-directory: ./client_term

    - name: Build client_gui (Ubuntu)
      run: cargo build --verbose
      working-directory: ./client_gui
  
  test_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test library (Ubuntu)
      run: cargo test --verbose

    - name: Test server (Ubuntu)
      run: cargo test --verbose
      working-directory: ./server
        
    - name: Test client_term (Ubuntu)
      run: cargo test --verbose
      working-directory: ./client_term

    - name: Test client_gui (Ubuntu)
      run: cargo test --verbose
      working-directory: ./client_gui
  
  build_windows:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build library (Windows)
      run: cargo build --verbose

    - name: Build server (Windows)
      run: cargo build --verbose
       working-directory: ./server
        
    - name: Build client_term (Windows)
      run: cargo build --verbose
      working-directory: ./client_term

    - name: Build client_gui (Windows)
      run: cargo build --verbose
      working-directory: ./client_gui

  test_windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test library (Windows)
      run: cargo test --verbose

    - name: Test server (Windows)
      run: cargo test --verbose
      working-directory: ./server
        
    - name: Test client_term (Windows)
      run: cargo test --verbose
      working-directory: ./client_term

    - name: Test client_gui (Windows)
      run: cargo test --verbose
      working-directory: ./client_gui